_target_: torch_seq_moo.tasks.amp.AMPTask
log_prefix: amp
min_len: 10
max_len: 60
num_start_examples: 512
batch_size: 16
max_score_per_dim: 1.0
score_max:
  - 1.0  # activity
  - 1.0  # safety
  - 1.0  # length
objectives:
  - activity
  - safety
  - length
eval_pref: # 没啥用的参数，默认是评估全部偏好，体现完整性
  - 0.4
  - 0.3
  - 0.3
allow_len_change: True
esm_model_path: /root/autodl-tmp/AMP_reward/esm2_650m_weights
amp_weight_path: /root/autodl-tmp/AMP_reward/amp_classifier_650M_best.pth
hemo_weight_path: /root/autodl-tmp/AMP_reward/hemolytic_classifier_650M_best.pth
