_target_: torch_seq_moo.algorithms.offline_mogfn.MOGFN
_recursive_: False
num_rounds: 64
num_gens: 16
random_action_prob: 0.05
max_len: ${task.max_len}
min_len: ${task.min_len}
eval_metrics: ["hypervolume", "r2", "hsri"]
batch_size: 256
reward_exp: 4
reward_min: 1e-80
reward_max: 100
sampling_temp: 1
train_steps: 10000
beta_use_therm: True
pref_use_therm: True
beta_cond: False
pref_cond: True
beta_scale: 1
beta_shape: 32
pref_alpha: [1.0,1.0,1.0]
pi_lr: 0.00001
z_lr: 0.0001
wd: 0.0001
beta_max: 56
therm_n_bins: 50
gen_clip: 10
encoder_obj: mlm
reward_type: convex # tchebycheff

sample_beta: 32

simplex_bins: 10
eval_freq: 500
k: 128
num_samples: 128
use_eval_pref: False
state_save_path: "."
num_pareto_points: 500
pareto_freq: 1000
unnormalize_rewards: False

use_offline: true
offline_data_path: /home/gml/GFN/mo_gfn/pre_train/pos_AMP_scored_filtered.csv
offline_batch_size: 128

use_new_eval: false # 新的评估方法
new_eval_num_samples: 5000
new_eval_save_path: "/home/gml/GFN/mo_gfn/results/new_eval_sequences.csv"

model:
  _target_: torch_seq_moo.algorithms.mogfn_utils.conditional_transformer.CondGFNTransformer
  max_len: ${task.max_len}
  vocab_size: 26
  num_actions: 21
  num_hid: 512
  num_layers: 3
  num_head: 16
  bidirectional: False
  dropout: 0.1
  batch_size: 128
