_target_: torch_seq_moo.tasks.nupack.NupackTask
objectives:
  - energy # DNA结构自由能
  - pins # 发夹结构数量
  - pairs # 配对结构数量
eval_pref: 
  - 0.5
  - 0.25
  - 0.25
score_max:
  - 60
  - 8
  - 16
# regex_list: !!null 并没什么用
min_len: 30
max_len: 30
num_start_examples: 512 # 没用
batch_size: 16
max_num_edits: null # 没用
max_ngram_size: 1
allow_len_change: True # 没用，没实现。。。
max_score_per_dim: 16 # 同样没用
